### ISSUE TITLE
 Prebuild devcontainer workflow should only run after a PR has been merged

### ISSUE THREAD

**Issue by heyajulia** [heyajulia/drmhbot#112]
As seen in #111, the prebuild workflow was run even on a PR.

**Comment by heyajulia** [comment]
Would this work?

```yaml
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/*
      - .devcontainer/*
  workflow_dispatch:
```
